/* ============================================
   Shared behaviour for blog / studio pages.
   The homepage has its own script.js — these pages only need nav + year.
   ============================================ */

const navToggle = document.getElementById('navToggle');
const navLinks = document.getElementById('navLinks');

if (navToggle && navLinks) {
  navToggle.addEventListener('click', () => {
    const open = navLinks.classList.toggle('open');
    navToggle.classList.toggle('open', open);
    navToggle.setAttribute('aria-expanded', String(open));
  });

  navLinks.querySelectorAll('a').forEach(link => {
    link.addEventListener('click', () => {
      navLinks.classList.remove('open');
      navToggle.classList.remove('open');
      navToggle.setAttribute('aria-expanded', 'false');
    });
  });
}

const yearEl = document.getElementById('year');
if (yearEl) yearEl.textContent = new Date().getFullYear();

/* ============================================
   Studio directory: search + district filter
   Cards are already in the DOM (generated by tools/build-studios.ps1) so they
   stay crawlable — this only shows and hides them.
   ============================================ */
const studioList = document.getElementById('studioList');

if (studioList) {
  const cards = Array.from(studioList.querySelectorAll('.studio-card'));
  const searchInput = document.getElementById('studioSearch');
  const chips = Array.from(document.querySelectorAll('.chip'));
  const countEl = document.getElementById('finderCount');
  const emptyEl = document.getElementById('finderEmpty');

  let activeFilter = 'all';

  function apply() {
    const q = (searchInput.value || '').trim().toLowerCase();
    let shown = 0;

    cards.forEach(card => {
      const matchesText = !q || card.dataset.search.includes(q);

      let matchesFilter;
      if (activeFilter === 'all') {
        matchesFilter = true;
      } else if (activeFilter === 'verified') {
        matchesFilter = card.dataset.verified === 'true';
      } else {
        matchesFilter = card.dataset.district === activeFilter;
      }

      const visible = matchesText && matchesFilter;
      card.hidden = !visible;
      if (visible) shown++;
    });

    countEl.textContent = shown === cards.length
      ? `Menampilkan semua ${cards.length} studio`
      : `Menampilkan ${shown} dari ${cards.length} studio`;

    emptyEl.hidden = shown > 0;
  }

  let debounce;
  searchInput.addEventListener('input', () => {
    clearTimeout(debounce);
    debounce = setTimeout(apply, 120);
  });

  chips.forEach(chip => {
    chip.addEventListener('click', () => {
      chips.forEach(c => c.classList.remove('is-active'));
      chip.classList.add('is-active');
      activeFilter = chip.dataset.filter;
      apply();
    });
  });

  apply();
}
